### ISSUE TITLE
Additional USWDS assets

### ISSUE THREAD

**Issue by robdecker** [JudicialCouncilOfCalifornia/courtyard-artifact#2]
SRL is still using Courtyard itself, but needs to be switched over to using this artifact. However, SRL is using additional sass partials that haven't been included in the [scripts](https://github.com/JudicialCouncilOfCalifornia/courtyard-artifact/blob/master/composer.json#L14-L16) portion of composer.json

Currently, `courtyard/node_modules/uswds/src/stylesheets/core` is included, but SRL also needs `courtyard/node_modules/uswds/src/stylesheets/packages/required`

Looks like we have two options here:

1. Add this new requirement as an additional rsync command
2. Remove `courtyard/node_modules/uswds/src/stylesheets/core` and add `courtyard/node_modules/uswds/src/stylesheets` to include all sass partials

Thoughts? @ivanbueno-jcc @melwong-jcc

**Comment by ivanbueno-jcc** [comment]
@robdecker 

Update this line:
https://github.com/JudicialCouncilOfCalifornia/courtyard/blob/01bb9575ec3a1e76c55cea68b02ba32f78aedab4/.github/workflows/create-artifact-from-development.yml#L31
To:
mkdir -p artifact/source/uswds/stylesheets && cp -R node_modules/uswds/src/stylesheets/* artifact/source/uswds/stylesheets/.
